package com.foursquare.server.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InternalOrderItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalOrderItemAllPropertiesEquals(InternalOrderItem expected, InternalOrderItem actual) {
        assertInternalOrderItemAutoGeneratedPropertiesEquals(expected, actual);
        assertInternalOrderItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalOrderItemAllUpdatablePropertiesEquals(InternalOrderItem expected, InternalOrderItem actual) {
        assertInternalOrderItemUpdatableFieldsEquals(expected, actual);
        assertInternalOrderItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalOrderItemAutoGeneratedPropertiesEquals(InternalOrderItem expected, InternalOrderItem actual) {
        assertThat(expected)
            .as("Verify InternalOrderItem auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalOrderItemUpdatableFieldsEquals(InternalOrderItem expected, InternalOrderItem actual) {
        assertThat(expected)
            .as("Verify InternalOrderItem relevant properties")
            .satisfies(e -> assertThat(e.getQty()).as("check qty").isEqualTo(actual.getQty()))
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalOrderItemUpdatableRelationshipsEquals(InternalOrderItem expected, InternalOrderItem actual) {
        assertThat(expected)
            .as("Verify InternalOrderItem relationships")
            .satisfies(e -> assertThat(e.getOrderItem()).as("check orderItem").isEqualTo(actual.getOrderItem()));
    }
}
