package com.foursquare.server.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InternalOrderHistoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalOrderHistoryAllPropertiesEquals(InternalOrderHistory expected, InternalOrderHistory actual) {
        assertInternalOrderHistoryAutoGeneratedPropertiesEquals(expected, actual);
        assertInternalOrderHistoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalOrderHistoryAllUpdatablePropertiesEquals(InternalOrderHistory expected, InternalOrderHistory actual) {
        assertInternalOrderHistoryUpdatableFieldsEquals(expected, actual);
        assertInternalOrderHistoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalOrderHistoryAutoGeneratedPropertiesEquals(InternalOrderHistory expected, InternalOrderHistory actual) {
        assertThat(expected)
            .as("Verify InternalOrderHistory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalOrderHistoryUpdatableFieldsEquals(InternalOrderHistory expected, InternalOrderHistory actual) {
        assertThat(expected)
            .as("Verify InternalOrderHistory relevant properties")
            .satisfies(e -> assertThat(e.getNote()).as("check note").isEqualTo(actual.getNote()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInternalOrderHistoryUpdatableRelationshipsEquals(InternalOrderHistory expected, InternalOrderHistory actual) {
        assertThat(expected)
            .as("Verify InternalOrderHistory relationships")
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getOrder()).as("check order").isEqualTo(actual.getOrder()));
    }
}
