package com.foursquare.server.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ParticipantAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantAllPropertiesEquals(Participant expected, Participant actual) {
        assertParticipantAutoGeneratedPropertiesEquals(expected, actual);
        assertParticipantAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantAllUpdatablePropertiesEquals(Participant expected, Participant actual) {
        assertParticipantUpdatableFieldsEquals(expected, actual);
        assertParticipantUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantAutoGeneratedPropertiesEquals(Participant expected, Participant actual) {
        assertThat(expected)
            .as("Verify Participant auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantUpdatableFieldsEquals(Participant expected, Participant actual) {
        assertThat(expected)
            .as("Verify Participant relevant properties")
            .satisfies(e -> assertThat(e.getIsAdmin()).as("check isAdmin").isEqualTo(actual.getIsAdmin()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertParticipantUpdatableRelationshipsEquals(Participant expected, Participant actual) {
        assertThat(expected)
            .as("Verify Participant relationships")
            .satisfies(e -> assertThat(e.getConversation()).as("check conversation").isEqualTo(actual.getConversation()));
    }
}
