package com.foursquare.server.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShipmentStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentStatusAllPropertiesEquals(ShipmentStatus expected, ShipmentStatus actual) {
        assertShipmentStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertShipmentStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentStatusAllUpdatablePropertiesEquals(ShipmentStatus expected, ShipmentStatus actual) {
        assertShipmentStatusUpdatableFieldsEquals(expected, actual);
        assertShipmentStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentStatusAutoGeneratedPropertiesEquals(ShipmentStatus expected, ShipmentStatus actual) {
        assertThat(expected)
            .as("Verify ShipmentStatus auto generated properties")
            .satisfies(e -> assertThat(e.getStatusCode()).as("check statusCode").isEqualTo(actual.getStatusCode()))
            .satisfies(e -> assertThat(e.getCreatedBy()).as("check createdBy").isEqualTo(actual.getCreatedBy()))
            .satisfies(e -> assertThat(e.getCreatedDate()).as("check createdDate").isEqualTo(actual.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentStatusUpdatableFieldsEquals(ShipmentStatus expected, ShipmentStatus actual) {
        assertThat(expected)
            .as("Verify ShipmentStatus relevant properties")
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentStatusUpdatableRelationshipsEquals(ShipmentStatus expected, ShipmentStatus actual) {}
}
